[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
    "python --version",
    "python -m pip --version",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd webapp/backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
