[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r webapp/backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd webapp/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
