[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "python --version",
    "pip --version",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd webapp/backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
